version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_container_capacidad
    restart: always
    environment:
      POSTGRES_DB: capacidad
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
    ports:
      - "5433:5433"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
